-- MySQL Script generated by MySQL Workbench
-- Wed Jul 13 11:08:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym` DEFAULT CHARACTER SET utf8 ;
USE `gym` ;

-- -----------------------------------------------------
-- Table `gym`.`admin_panel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`admin_panel` (
  `id_admin` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_admin` VARCHAR(45) NOT NULL,
  `password_admin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`trainer` (
  `id_trainer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_trainer` VARCHAR(50) NOT NULL,
  `lastName_trainer` VARCHAR(60) NOT NULL,
  `trainerID` FLOAT(4) UNSIGNED NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_trainer`),
  UNIQUE INDEX `trainerID_UNIQUE` (`trainerID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`member` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_member` VARCHAR(50) NOT NULL,
  `lastName_member` VARCHAR(60) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `memberID` FLOAT(3) UNSIGNED NOT NULL,
  `trainer_id_trainer` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `memberID_UNIQUE` (`memberID` ASC) VISIBLE,
  INDEX `fk_member_Trainer_idx` (`trainer_id_trainer` ASC) VISIBLE,
  CONSTRAINT `fk_member_Trainer`
    FOREIGN KEY (`trainer_id_trainer`)
    REFERENCES `gym`.`trainer` (`id_trainer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gym`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gym`.`payment` (
  `id_payment` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` INT(4) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `payment_type` VARCHAR(30) NOT NULL,
  `member_id_member` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_payment`),
  INDEX `fk_payment_member1_idx` (`member_id_member` ASC) VISIBLE,
  CONSTRAINT `fk_payment_member1`
    FOREIGN KEY (`member_id_member`)
    REFERENCES `gym`.`member` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
